### ISSUE TITLE
SAS catalog: value label sets with long names aren't being matched

### ISSUE THREAD

**Issue by evanmiller** [hadley/haven#121]
SAS catalog files can name their formats (value label sets) with both 8-byte short name and a 32-byte long name. At present ReadStat is returning the short name, which may not be the correct behavior. @cullenjd has reported that his value labels are not being properly applied (see previous discussion at #34). It is likely an issue with ReadStat but could also be something with haven.

**Comment by evanmiller** [comment]
I've pushed a possible fix to ReadStat here: https://github.com/WizardMac/ReadStat/commit/ac1a2db4dad4c47e6cb082416c3fe01d3de60f1c

**Comment by evanmiller** [comment]
@cullenjd Please try:

```{R}
devtools::install_github("evanmiller/haven", ref="update-readstat")
```

**Comment by cullenjd** [comment]
@evanmiller - I updated but I'm still not getting the value labels from the catalog file.

> table(opdata$workstat)

>   0    1    2    3 
>5604 2441    67   42 


Should be:

> "No"    "Yes"    "Don't Know"   "Refused"
>5604 2441    67   42

**Comment by evanmiller** [comment]
@cullenjd - Do you have a small sample data file you can share?

**Comment by cullenjd** [comment]
@evanmiller 
https://www.dropbox.com/s/hdg3ng810wgyrjv/clear.sas7bdat?dl=0

**Comment by evanmiller** [comment]
I am seeing the labels:

```
> df$workstat
<Labelled>
  [1]  2  0  1  0  0  0  0  1  0  0  0  0  0  1  1  0  0  0  1  0  0  0  0  0  0  1  0  0  0  0  1  0  0  0  0  1  0  0  0  0  0  0  0  1  1  0  0  0  1  0  1
 [52]  0  1  0  0  0  0  1  1  1 NA  1  0  1  0  0  0  0  1  1  1  0  0  0  1  0  0  0  0  0 NA  0  0  1  0 NA  0  0  0  0  0  0  1  0  0  0  0  0  0  0
attr(,"label")
[1] workstat: H1. At the time of your fracture, were you working full- or part-time for pay?

Labels:
 value                                  label is_na
     1                                  A.Yes FALSE
     0                                   B.No FALSE
     2                           C.Don't know FALSE
     3 D.Patient declined to answer (Refused) FALSE
```

It appears the `table` doesn't produce labels -- I think this is a separate issue (@hadley?).

In any event it appears that labels are imported correctly with the patch. I will leave this issue open until the changes are merged into haven/master.

**Comment by gergness** [comment]
@cullenjd - the variables are imported as `labelled` class vectors and require some more manipulation before you can refer to them by their labelled values. I think the idea is that haven imports the data in this intermediate form, and expects the user to convert them to more standard R structures that suit the particular analysis. 

In your example, use `as_factor()` to convert the variable to a factor, and `table()` will use the labels.

```r 
opdata$workstat <- as_factor(opdata$workstat)
table(opdata$workstat)
```
