### ISSUE TITLE
Error after importing data 

### ISSUE THREAD

**Issue by BERENZ** [hadley/haven#26]
I've got a following error after importing Social Diagnosis survey dataset (link to data - http://www.diagnoza.com/data/database/2000_2013/SOCIAL_DIAGNOSIS_H_2000_2013_SAV.zip)  

```
> library(dplyr)
> library(haven)
> fname <- '~/Downloads/SOCIAL_DIAGNOSIS_H_2000_2013.SAV'
> dsin <- read_spss(path = fname)
> class(dsin)
[1] "tbl_df"     "tbl"        "data.frame"
> head(dsin)
Error: `x` and `labels` must be same type
```
I've got also an error after applying `count` function from `dplyr` but this is probably that the class `labelled` is not implemented in `dplyr`?

```
> d <- dsin %>% count(gdtyp_11)
Error: column 'NUMER_2000_2013' of type numeric has unsupported attributes: label

```

**Comment by hadley** [comment]
Hmmmm, it's because I've somewhat oversimplified the parsing. Here's a simpler reprex:

```R
tmp <- tempfile()

df <- data.frame(labelled(1:5, c("a" = 2L)))
write_sav(df, tmp)
read_sav(tmp)
```

**Comment by BERENZ** [comment]
As I see the error occurs when ```dplyr``` package is loaded.

```
> library(haven)
Warning message:
package ‘haven’ was built under R version 3.1.3 
> 
> tmp <- tempfile()
> 
> df <- data.frame(labelled(1:5, c("a" = 2L)))
> write_sav(df, tmp)
> read_sav(tmp)
  x..i..
1      1
2      2
3      3
4      4
5      5
> 
> library(dplyr)

Attaching package: ‘dplyr’

The following object is masked from ‘package:stats’:

    filter

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> 
> read_sav(tmp)
Source: local data frame [5 x 1]

Error: `x` and `labels` must be same type
> 
```

I'm using RStudio 0.99.318 and below is my session info

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.1    haven_0.1.0    devtools_1.7.0

loaded via a namespace (and not attached):
[1] assertthat_0.1 DBI_0.3.1      magrittr_1.5   parallel_3.1.2 Rcpp_0.11.4.7  tools_3.1.2  
```

**Comment by bquast** [comment]
I something to add to this which I find quite curious. I run into the same problem with a set of stata12 files, using head, view, etc.

After closing and opening RStudio with the View tab still open, it renders correctly (even though it is no longer in the global environment). 

This works on both Windows 7 and Arch Linux, session infos below.

Windows 7, RStudio 0.99.325
```
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.1.2
```

Arch Linux, RStudio, 0.99.315
```
R version 3.1.2 (2014-10-31)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.1.2
```

**Comment by gorcha** [comment]
(Hadley you've no doubt already figured this out but...)

The issue is that when it's read in the values are `numeric` but the label type is `integer`. Because of the way the label creation is implemented in `DfBuilder.cpp` numeric labels will always be class `integer` when they're read into R. This doesn't become an issue until the `labelled()` function is called (like when a labelled vector is subsetted).

I've submitted a quick fix as a pull request that seems to solve the problem.

**Comment by hadley** [comment]
Fixed by #44

**Comment by sebastianbarfort** [comment]
I keep getting this error when I work with the World Value Survey. When I download the data in `.dta` [here](http://www.worldvaluessurvey.org/WVSDocumentationWV6.jsp) and load it using `read_dta` using the latest version of `haven` from CRAN, I get `Error: `x` and `labels` must be same type`.

**Comment by sjkiss** [comment]
I'm still getting this error with a Stata_13 data set. 
RStudio 0.98.1103

    R version 3.2.3 (2015-12-10)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.11.2 (El Capitan)

    locale:
    [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

    attached base packages:
    [1] graphics  grDevices utils     datasets 
    [5] stats     methods   base     

    other attached packages:
    [1] haven_0.2.0    tidyr_0.3.1   
    [3] foreign_0.8-66 dplyr_0.4.3   
    [5] ggplot2_1.0.1  car_2.1-1     

    loaded via a namespace (and not attached):
    [1] Rcpp_0.12.2        magrittr_1.5      
    [3] splines_3.2.3      MASS_7.3-45       
    [5] munsell_0.4.2      colorspace_1.2-6  
    [7] lattice_0.20-33    R6_2.1.1          
    [9] minqa_1.2.4        stringr_1.0.0     
    [11] plyr_1.8.3         tools_3.2.3       
    [13] nnet_7.3-11        parallel_3.2.3    
    [15] pbkrtest_0.4-4     grid_3.2.3        
    [17] nlme_3.1-122       gtable_0.1.2      
    [19] mgcv_1.8-9         quantreg_5.19     
    [21] DBI_0.3.1          MatrixModels_0.4-1
    [23] assertthat_0.1     lme4_1.1-10       
    [25] digest_0.6.8       Matrix_1.2-3      
    [27] nloptr_1.0.4       reshape2_1.4.1    
    [29] stringi_1.0-1      scales_0.3.0      
    [31] SparseM_1.7        proto_0.3-10

**Comment by hadley** [comment]
Please don't post on closed issues as I'm unlikely to notice them when I'm preparing for the next release (and often it's a different underlying bug anyway). Instead create a new issue with a minimal reproducible example. Don't include session info unless specifically asked for it.
