### ISSUE TITLE
Error: `x` and `labels` must be same type

### ISSUE THREAD

**Issue by christophergandrud** [hadley/haven#86]
Using `read_dta` on this Stata file produces odd output:

http://siteresources.worldbank.org/INTRES/Resources/469232-1107449512766/DPI2012.dta

One possible indication of the issues is running `summary` on the supposed data frame that `read_dta` creates produces:

```{S}
Error: `x` and `labels` must be same type
```

**Comment by jon-mellon** [comment]
I'm sure there will be a more permanent fix, but the following function I wrote cleared up this problem for me and might be useful as a stopgap:

```
labelDataset <- function(data) {
  correctLabel <- function(x) {

    if(!is.null(attributes(x)$labels)) {
      class(attributes(x)$labels) <- typeof(x)
    }
    return(x)
  }
  for(i in colnames(data)) {
    print(i)
    data[, i] <- correctLabel(data[, i])
  }
  return(data)
}
```

**Comment by christophergandrud** [comment]
Thanks. This largely addresses the issue. Though it would be nice if it was done internally.

**Comment by jabranham** [comment]
I was having the same issue with stata data and this function solved it. Thanks!

**Comment by hadley** [comment]
Fixed in #110

**Comment by ewenharrison** [comment]
I'm still having issues with this. I have a data.frame with variables of class `labelled` which I would rather keep. Still conflicting though. Any ideas appreciated. I'm not using `haven` but it loads with `tidyverse` hence issue. 

```
# Simple linear regression
data(mtcars)
lm(mpg~cyl, data=mtcars) # Works as expected

# Add attribute
class(mtcars$mpg) = c("labelled",class(mtcars$mpg))
lm(mpg~cyl, data=mtcars) # Works as expected

library(haven)
lm(mpg~cyl, data=mtcars) #Error: `x` and `labels` must be same type
```

**Comment by bac3917** [comment]
I'm running into this issue as well, running a basic subset command on a df.

**Comment by hadley** [comment]
This is fixed in the _development_ version; you'll need to install that if you want the fix.  You can track progress of the release at https://github.com/tidyverse/haven/issues/399
